### ISSUE TITLE
Why we need username input?

### ISSUE THREAD

**Issue by evrpress** [syamilmj/Aqua-Verifier#4]
Wonder why we require the username on purchase validation. The username is included in the purchase info.

I suggest to complete remove the username input and request only purchase code. This reduces some errors and users don't have to enter less

**Comment by syamilmj** [comment]
I think the two-tier validation inputs provides some extra measure for security.

**Comment by evrpress** [comment]
If someone has the purchasecode it's easy to get the username as well. Also you can't create a new account with an existing purchasecode

**Comment by Firestorm-Graphics** [comment]
i personally recommend as many fields as possible for security, theres similar scripts out there which have been compromised before, and they have 2 fields.

**Comment by evrpress** [comment]
I just would like to make the registration progress as simple as possible. This in my mind the fastest way is only to ask for the purchasecode.

As mentioned above I think if someone has the purchasecode it's not hard to get the username as well

**Comment by syamilmj** [comment]
@revaxarts Just merged your pull request, very clean and useful. Thanks! - https://github.com/sy4mil/Aqua-Verifier/pull/5

Cheers :)
